# Generated by Django 5.1.6 on 2025-02-23 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
